version: "2"

services:
  service:
      build:
        dockerfile: ./docker/Local.Dockerfile
        context: ./service
      ports:
        - 8080:8080

  db:
    image: amazon/dynamodb-local
    ports:
    - "8000:8000"

  ui:
    build: ./ui
    ports:
      - 5000:5000
      - 3000:3000
    volumes: 
      ./ui:/usr/src/app
    environment: 
      BUILD_ENV: local